spring:
  main:
    web-application-type: none
  output:
    ansi:
      enabled: always

warthog:
  user:
    directory: user
  overview:
    rows: 50
    truncate-after: 0
  spark:
    threads: 4
    ui: false
